import Head from 'next/head';

import { Footer, NavBar } from '@/components/common';
import { PropsWithChildren } from 'react';

interface Props {
  pageTitle: string;
}

/** 2023/06/30 - page 레이아웃 구성 - by leekoby */
const PageLayout: React.FC<PropsWithChildren<Props>> = ({ children, pageTitle }): JSX.Element => {
  return (
    <>
      <div className='page-layout pb-8 mx-auto max-w-7xl px-4 space-y-8 sm:px-6 lg:px-8'>
        <Head>
          <title>{pageTitle}</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/koby-favicon.ico' />
        </Head>

        <div className='relative bg-white pb-8   lg:w-full lg:max-w-2xl'>
          {/* Navbar*/}
          <NavBar />
        </div>

        <div className='mx-auto max-w-2xl px-4 sm:px-6 lg:max-w-7xl'>{children}</div>
      </div>
      {/* Footer */}
      <Footer />
    </>
  );
};

export default PageLayout;
